; ball.s — Boing-style ball, a blitter object spun by cycling its colours
; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
;
; Generated by tools/mkball.py.  Edit the generator, not this file.
;
; 64x64 pixels in 4 bitplanes, interleaved a row at a time — plane 0's
; 10 bytes for the row, then plane 1's, 2's, 3's, then the next row.  Every row
; carries 1 blank word on the right so the object can be blitted at any
; pixel position, which makes a row 40 bytes over all four planes.  The mask
; is a single plane in the same shape, 1 where the ball is opaque.
;
; The bitmap never changes.  The ball's surface is cut into bands of longitude
; all 11.250 degrees wide, each drawn in its own pen, so turning the ball by one
; band lands every boundary where the one next door was.  Writing the next row
; of BallCycle to COLOR06 upwards is that turn.  8 steps take the ball round
; by 90.0 degrees and leave the registers as they started, so the table loops.
;
; The ball uses pens 6 to 13 and nothing else.  Pen 0 shows through as the
; background.  Checks are 8 around the sphere and 6 rows of latitude, the axis
; leaning 17 degrees.  Latitude does not turn, only longitude.
;
; The checks are $F28 against $FFF.  Only this table carries them — the
; bitmaps hold pen numbers, so recolouring the ball leaves both binaries alone.
;
; Both halves of the object are word aligned, so the blitter can be pointed
; straight at them.
; ---------------------------------------------------------------------------

BALL_WIDTH_W        EQU 5                   ; words per bitplane row, margin included
BALL_WIDTH_PX       EQU 64                  ; the ball itself, without the margin
BALL_HEIGHT         EQU 64                  ; pixel rows
BALL_PLANES         EQU 4
BALL_ROW_BYTES      EQU BALL_WIDTH_W*2      ; 10 bytes, one plane of one row
BALL_ROW_STRIDE     EQU BALL_ROW_BYTES*BALL_PLANES  ; 40 bytes, all planes of a row
BALL_BYTES          EQU BALL_ROW_STRIDE*BALL_HEIGHT ; 2560
BALL_MASK_BYTES     EQU BALL_ROW_BYTES*BALL_HEIGHT  ; 640

BALL_PEN_FIRST      EQU 6                   ; lowest colour register it uses
BALL_PENS           EQU 8                   ; registers 6 to 13 inclusive
BALL_STEPS          EQU 8                   ; rows in BallCycle
BALL_STEP_BYTES     EQU BALL_PENS*2         ; one row of BallCycle
BALL_CYCLE_BYTES    EQU BALL_STEP_BYTES*BALL_STEPS

                    CNOP    0,2
BallData:
                    INCBIN  "assets/ball.bin"
BallDataEnd:

                    CNOP    0,2
BallMask:
                    INCBIN  "assets/ball_mask.bin"
BallMaskEnd:

; One row per step, 8 words a row, to be written to COLOR06 upwards.
                    CNOP    0,2
BallCycle:
                    dc.w    $F28,$F28,$F28,$F28,$FFF,$FFF,$FFF,$FFF   ; step 0
                    dc.w    $FFF,$F28,$F28,$F28,$F28,$FFF,$FFF,$FFF   ; step 1
                    dc.w    $FFF,$FFF,$F28,$F28,$F28,$F28,$FFF,$FFF   ; step 2
                    dc.w    $FFF,$FFF,$FFF,$F28,$F28,$F28,$F28,$FFF   ; step 3
                    dc.w    $FFF,$FFF,$FFF,$FFF,$F28,$F28,$F28,$F28   ; step 4
                    dc.w    $F28,$FFF,$FFF,$FFF,$FFF,$F28,$F28,$F28   ; step 5
                    dc.w    $F28,$F28,$FFF,$FFF,$FFF,$FFF,$F28,$F28   ; step 6
                    dc.w    $F28,$F28,$F28,$FFF,$FFF,$FFF,$FFF,$F28   ; step 7
BallCycleEnd:
