; chime.s — boot chime sample for Paula
; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
;
; Generated by tools/mkchime.py.  Edit the generator, not this file.
;
; 8-bit signed mono, 14187.6 Hz on a PAL machine.  Paula reads the sample
; over DMA, so the bytes have to be in chip RAM and word aligned — copy
; CHIME_LEN_BYTES from ChimeData to a chip RAM buffer, point the channel at the
; copy, and write CHIME_LEN_WORDS to the channel's length register.
;
; DMA repeats the sample for as long as the channel is on.  One chime is
; start, wait CHIME_MS, stop.  The sample ends in silence, so a wait that
; overruns by a frame or two makes no sound.
; ---------------------------------------------------------------------------

CHIME_LEN_WORDS     EQU 3547         ; channel length register
CHIME_LEN_BYTES     EQU 7094         ; bytes to copy into chip RAM
CHIME_PERIOD        EQU 250          ; PAL, 14187.6 Hz
CHIME_PERIOD_NTSC   EQU 252          ; NTSC, same pitch
CHIME_MS            EQU 501          ; play time, about 25 PAL frames

                    CNOP    0,2
ChimeData:
                    INCBIN  "assets/chime.bin"
ChimeDataEnd:
