; logo.s — One ROM logo, a blitter object
; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
;
; Generated by tools/mkimage.py.  Edit the generator and re-run it, not
; this file.  tools/README.md has the command.
;
; From logo_112x92.png, area-averaged to 112x92 and then snapped to the
; nearest of the pens below, so the object holds no colour outside them.
;
; 112x92 pixels in 4 bitplanes, interleaved a row at a time — plane 0's 16
; bytes for the row, then plane 1's, 2's, 3's, then the next row.  Every
; row carries 1 blank word on the right so the object can be blitted at any
; pixel position, which makes a row 64 bytes over all four planes.  The
; mask is a single plane in the same shape, 1 where the object is opaque
; and 0 where the background shows through.  Words are big-endian.
;
; Both halves of the object are word aligned, so the blitter can be pointed
; straight at them.
; -------------------------------------------------------------------------

LOGO_WIDTH_W        EQU 8                       ; words per bitplane row, margin included
LOGO_WIDTH_PX       EQU 112                     ; the object itself, without the margin
LOGO_HEIGHT         EQU 92                      ; pixel rows
LOGO_PLANES         EQU 4
LOGO_ROW_BYTES      EQU LOGO_WIDTH_W*2          ; 16 bytes, one plane of one row
LOGO_ROW_STRIDE     EQU LOGO_ROW_BYTES*LOGO_PLANES  ; 64 bytes, all planes of a row
LOGO_BYTES          EQU LOGO_ROW_STRIDE*LOGO_HEIGHT  ; 5888
LOGO_MASK_BYTES     EQU LOGO_ROW_BYTES*LOGO_HEIGHT  ; 1472
LOGO_BLIT_ROWS      EQU LOGO_HEIGHT*LOGO_PLANES  ; 368, one blit copies all four planes

; Colour registers, $0RGB.  The object uses these pens and no others.
LOGO_PEN0           EQU $0000                   ; #000000
LOGO_PEN2           EQU $0FB0                   ; #FFBB00
LOGO_PEN3           EQU $0111                   ; #111111
LOGO_PEN4           EQU $0333                   ; #333333
LOGO_PEN5           EQU $0DDD                   ; #DDDDDD

                    CNOP    0,2
LogoData:
                    INCBIN  "assets/logo.bin"
LogoDataEnd:

                    CNOP    0,2
LogoMask:
                    INCBIN  "assets/logo_mask.bin"
LogoMaskEnd:
