; tagline_wide.s — the tagline on one line, a blitter object
; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
;
; Generated by tools/mkimage.py.  Edit the generator and re-run it, not
; this file.  tools/README.md has the command.
;
; "One ROM to rule them all" set in Michroma-Regular.ttf at 18 point and
; thresholded to one bit.  The ink covers 282x14 pixels, centred in the
; 288-pixel row.
; Each line is drawn as one string and the finished bitmap is then shared
; out by column, so a character in its own pen is the same pixels it would
; have been in any other — nothing moves, respaces or changes shape.  Pen 5
; sets the text, except 'O' at index 5 in pen 2.
; Pens 2, 5 are set, and all four planes are stored so the blit matches the
; other objects on this screen.
;
; 288x14 pixels in 4 bitplanes, interleaved a row at a time — plane 0's 38
; bytes for the row, then plane 1's, 2's, 3's, then the next row.  Every
; row carries 1 blank word on the right so the object can be blitted at any
; pixel position, which makes a row 152 bytes over all four planes.  The
; mask is a single plane in the same shape, 1 where the object is opaque
; and 0 where the background shows through.  Words are big-endian.
;
; Both halves of the object are word aligned, so the blitter can be pointed
; straight at them.
; -------------------------------------------------------------------------

TAGLINE_WIDE_WIDTH_W EQU 19                     ; words per bitplane row, margin included
TAGLINE_WIDE_WIDTH_PX EQU 288                   ; the object itself, without the margin
TAGLINE_WIDE_HEIGHT EQU 14                      ; pixel rows
TAGLINE_WIDE_PLANES EQU 4
TAGLINE_WIDE_ROW_BYTES EQU TAGLINE_WIDE_WIDTH_W*2  ; 38 bytes, one plane of one row
TAGLINE_WIDE_ROW_STRIDE EQU TAGLINE_WIDE_ROW_BYTES*TAGLINE_WIDE_PLANES  ; 152 bytes, all planes of a row
TAGLINE_WIDE_BYTES  EQU TAGLINE_WIDE_ROW_STRIDE*TAGLINE_WIDE_HEIGHT  ; 2128
TAGLINE_WIDE_MASK_BYTES EQU TAGLINE_WIDE_ROW_BYTES*TAGLINE_WIDE_HEIGHT  ; 532
TAGLINE_WIDE_BLIT_ROWS EQU TAGLINE_WIDE_HEIGHT*TAGLINE_WIDE_PLANES  ; 56, one blit copies all four planes

; Colour registers, $0RGB.  The object uses these pens and no others.
TAGLINE_WIDE_PEN0   EQU $0000                   ; #000000
TAGLINE_WIDE_PEN2   EQU $0FB0                   ; #FFBB00
TAGLINE_WIDE_PEN5   EQU $0DDD                   ; #DDDDDD

                    CNOP    0,2
TaglineWideData:
                    INCBIN  "assets/tagline_wide.bin"
TaglineWideDataEnd:

                    CNOP    0,2
TaglineWideMask:
                    INCBIN  "assets/tagline_wide_mask.bin"
TaglineWideMaskEnd:
