#!/usr/bin/env python3
# mkpointer.py - generate the mouse pointer hardware sprite
# Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
#
# An Amiga sprite is 16 pixels wide and any number of rows tall.  Its data is
# two control words, then two words per row - one for each of the sprite's two
# bitplanes - then two zero words to end it.  The two planes give each pixel a
# value of 0 to 3, where 0 is transparent and 1 to 3 pick COLOR17, COLOR18 and
# COLOR19.
#
# The control words carry the sprite's position and height.  The application
# rewrites them every frame as the pointer moves, so the two written here are
# zero and exist only to hold the space.
#
# The shape below is written as text because that is the only sane way to edit
# it.

import sys

# . transparent, 1 outline, 2 fill, 3 the third sprite colour
#
# An arrow with its tip at the top left, outlined so it stays visible over the
# logo and the ball as well as over the background.
SHAPE = """
1...............
11..............
121.............
1221............
12221...........
122221..........
1222221.........
12222221........
122222221.......
1222222221......
122222111111....
1221221.........
121.1221........
11..1221........
.....1221.......
......11........
"""


def main():
    if len(sys.argv) != 2:
        print("usage: mkpointer.py <output.s>", file=sys.stderr)
        return 1

    rows = [r for r in SHAPE.strip().splitlines()]
    height = len(rows)
    for n, r in enumerate(rows):
        if len(r) != 16:
            print(f"row {n} is {len(r)} pixels, must be 16", file=sys.stderr)
            return 1
        if set(r) - set(".123"):
            print(f"row {n} has a character that is not . 1 2 or 3",
                  file=sys.stderr)
            return 1

    lines = []
    for r in rows:
        a = b = 0
        for x, c in enumerate(r):
            v = 0 if c == "." else int(c)
            bit = 15 - x
            if v & 1:
                a |= 1 << bit
            if v & 2:
                b |= 1 << bit
        lines.append((a, b, r))

    with open(sys.argv[1], "w") as f:
        f.write("; pointer.s - mouse pointer hardware sprite\n")
        f.write("; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>\n")
        f.write(";\n")
        f.write("; Generated by tools/mkpointer.py.  Edit the shape there.\n")
        f.write(";\n")
        f.write("; Sprite 0.  Two control words, then two words a row, then\n")
        f.write("; two zero words to end it.  The control words are written\n")
        f.write("; at run time as the pointer moves, so they start at zero.\n")
        f.write("; Pixel values 1 to 3 pick COLOR17, COLOR18 and COLOR19.\n")
        f.write("; ------------------------------------------------------\n\n")
        f.write(f"POINTER_HEIGHT      EQU {height}\n")
        f.write("POINTER_WIDTH       EQU 16\n")
        f.write(f"POINTER_BYTES       EQU {(height + 2) * 4}\n")
        f.write("POINTER_HOT_X       EQU 0             ; the tip, in the shape\n")
        f.write("POINTER_HOT_Y       EQU 0\n\n")
        f.write("                    CNOP    0,2\n")
        f.write("PointerSprite:\n")
        f.write("                    dc.w    $0000,$0000       ; control words\n")
        for a, b, r in lines:
            f.write(f"                    dc.w    ${a:04X},${b:04X}"
                    f"       ; {r}\n")
        f.write("                    dc.w    $0000,$0000       ; end of sprite\n")
        f.write("PointerSpriteEnd:\n")

    print(f"wrote {sys.argv[1]}: {height} rows, {(height + 2) * 4} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
