; disc_glyphs.s — the LED disc, as characters
; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
;
; Generated by tools/gen_disc.py.  Do not edit: change the generator.
;
; The disc is an ellipse 13 cells across and 11 down, sampled per pixel, so
; it is a circle rather than the octagon the ROM character set can manage.
; Below full brightness it is the same ellipse ANDed with a halftone lattice,
; which is why dimming never changes its shape.
;
; 143 cells, 41 distinct shapes, 111 characters over 3 brightness levels.

    .include "led_defs.s"

.rodata

; The class of every cell, row by row.
.export disc_class
disc_class:
    .byte 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0
    .byte 0, 10, 11, 5, 5, 5, 5, 5, 5, 5, 12, 13, 0
    .byte 14, 15, 5, 5, 5, 5, 5, 5, 5, 5, 5, 16, 17
    .byte 18, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 19
    .byte 20, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 21
    .byte 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5
    .byte 22, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 23
    .byte 24, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 25
    .byte 26, 27, 5, 5, 5, 5, 5, 5, 5, 5, 5, 28, 29
    .byte 0, 30, 31, 5, 5, 5, 5, 5, 5, 5, 32, 33, 0
    .byte 0, 0, 34, 35, 36, 37, 5, 38, 39, 40, 41, 0, 0

; What each class is drawn as, one table per brightness level.
.export disc_level_lo
.export disc_level_hi
disc_level_0:
    .byte $20, $40, $41, $42, $43, $44, $45, $46, $47, $40, $48, $49
    .byte $4A, $4B, $40, $4C, $4D, $4E, $4F, $50, $51, $52, $53, $54
    .byte $55, $56, $57, $58, $54, $59, $5A, $5B, $5C, $5D, $40, $5E
    .byte $5F, $44, $44, $60, $61, $62
disc_level_1:
    .byte $20, $63, $64, $65, $66, $67, $68, $69, $6A, $40, $6B, $6C
    .byte $6D, $6E, $6F, $70, $71, $72, $73, $74, $75, $76, $77, $78
    .byte $79, $7A, $7B, $7C, $7D, $59, $7E, $7F, $C0, $C1, $40, $C2
    .byte $C3, $C4, $C5, $C6, $C7, $62
disc_level_2:
    .byte $20, $63, $C8, $C9, $CA, $CB, $CC, $CD, $CE, $CF, $D0, $D1
    .byte $D2, $D3, $D4, $D5, $D6, $D7, $D8, $D9, $DA, $DB, $DC, $DD
    .byte $DE, $DF, $E0, $E1, $E2, $E3, $E4, $E5, $E6, $E7, $E8, $E9
    .byte $EA, $EB, $EC, $ED, $EE, $62

disc_level_lo:
    .byte <disc_level_0, <disc_level_1, <disc_level_2
disc_level_hi:
    .byte >disc_level_0, >disc_level_1, >disc_level_2

; The 11 shapes every other shape is mirrored from, eight rows each.
.export disc_gen
disc_gen:
    .byte $00, $00, $00, $00, $00, $00, $00, $01
    .byte $00, $00, $00, $00, $07, $1F, $7F, $FF
    .byte $00, $01, $1F, $FF, $FF, $FF, $FF, $FF
    .byte $0F, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .byte $00, $00, $00, $00, $00, $01, $07, $0F
    .byte $07, $0F, $3F, $7F, $FF, $FF, $FF, $FF
    .byte $00, $00, $00, $00, $00, $01, $01, $03
    .byte $1F, $3F, $3F, $7F, $FF, $FF, $FF, $FF
    .byte $07, $07, $0F, $0F, $1F, $1F, $1F, $3F
    .byte $3F, $3F, $7F, $7F, $7F, $7F, $FF, $FF

; One byte per class from class 1 up.  Bits 7-2 are the generator's index.
; Bit 0 mirrors left to right and bit 1 top to bottom.
.export disc_shape
.export disc_shape_end
disc_shape:
    .byte $00, $04, $08, $0C, $10, $0D, $09, $05, $01, $14, $18, $19
    .byte $15, $1C, $20, $21, $1D, $24, $25, $28, $29, $2A, $2B, $26
    .byte $27, $1E, $22, $23, $1F, $16, $1A, $1B, $17, $02, $06, $0A
    .byte $0E, $0F, $0B, $07, $03
disc_shape_end:

; The brightness masks, eight rows each, in level order.
.export disc_dither
disc_dither:
    .byte $AA, $00, $AA, $00, $AA, $00, $AA, $00
    .byte $AA, $55, $AA, $55, $AA, $55, $AA, $55
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

