#!/usr/bin/env python3
"""Generate the LED disc's character set.

The ROM character set has four diagonals and nothing else, so a disc built out
of it is an octagon.  The VIC can take its characters from RAM instead, and
this works out what those characters have to be: an ellipse 13 cells across and
11 down, 104 by 88 pixels, sampled per pixel.

Three brightness levels, because a C64 cell has one colour and no brightness.
Below full the disc is an ordered dither, which is the same ellipse ANDed with
a 4x4 Bayer pattern, so the silhouette never changes with brightness.

Writes an assembler source file: the class of every cell, the character code of
every class at every level, and the bitmaps themselves.

Two files come out: an include of the sizes, which led_defs.s pulls in so that
charset.s knows where the characters go, and the tables themselves.

Usage: gen_disc.py <output.s>   (the include is written alongside it as .inc)
"""
import sys

W, H = 13, 11
PW, PH = W * 8, H * 8
RX, RY = PW / 2.0, PH / 2.0

# Character codes free for the disc.  $00-$3F are copied from the character ROM
# and $80-$BF are their inverses, which is what reverse video needs.
FREE = list(range(0x40, 0x80)) + list(range(0xC0, 0x100))

BAYER = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]


def dither(threshold):
    return tuple(
        sum(1 << (7 - px) for px in range(8) if BAYER[py % 4][px % 4] < threshold)
        for py in range(8)
    )


LEVELS = [dither(4), dither(8), (255,) * 8]      # a quarter, a half, solid


def cell_mask(col, row):
    rows = []
    for py in range(8):
        b = 0
        for px in range(8):
            x = col * 8 + px + 0.5 - RX
            y = row * 8 + py + 0.5 - RY
            if (x / RX) ** 2 + (y / RY) ** 2 <= 1.0:
                b |= 1 << (7 - px)
        rows.append(b)
    return tuple(rows)


def main(path):
    cells = [[cell_mask(c, r) for c in range(W)] for r in range(H)]
    empty = (0,) * 8

    # One class per distinct cell shape.  Class 0 is the cell the disc never
    # reaches, which is a space at every level and needs no character of its own.
    classes = [empty]
    for row in cells:
        for m in row:
            if m not in classes:
                classes.append(m)

    # Deduplicate across levels as well: a shape ANDed with a dither often lands
    # on a bitmap some other shape already produced.
    codes = {}
    order = []
    level_tables = []
    for lv in LEVELS:
        table = []
        for cls in classes:
            if cls == empty:
                table.append(0x20)
                continue
            bits = tuple(a & b for a, b in zip(cls, lv))
            if bits not in codes:
                if len(order) >= len(FREE):
                    sys.exit("out of character codes: %d needed" % (len(order) + 1))
                codes[bits] = FREE[len(order)]
                order.append(bits)
            table.append(codes[bits])
        level_tables.append(table)

    out = []
    w = out.append
    w("; disc_glyphs.s — the LED disc, as characters")
    w("; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>")
    w(";")
    w("; Generated by tools/gen_disc.py.  Do not edit: change the generator.")
    w(";")
    w("; The disc is an ellipse %d cells across and %d down, sampled per pixel, so" % (W, H))
    w("; it is a circle rather than the octagon the ROM character set can manage.")
    w("; Below full brightness it is the same ellipse ANDed with a halftone lattice,")
    w("; which is why dimming never changes its shape.")
    w(";")
    w("; %d cells, %d distinct shapes, %d characters over %d brightness levels."
      % (W * H, len(classes) - 1, len(order), len(LEVELS)))
    w("")
    w("    .include \"led_defs.s\"")
    w("")
    w(".rodata")
    w("")
    w("; The class of every cell, row by row.")
    w(".export disc_class")
    w("disc_class:")
    for row in cells:
        w("    .byte " + ", ".join("%d" % classes.index(m) for m in row))
    w("")
    w("; What each class is drawn as, one table per brightness level.")
    w(".export disc_level_lo")
    w(".export disc_level_hi")
    for i, table in enumerate(level_tables):
        w("disc_level_%d:" % i)
        for j in range(0, len(table), 12):
            w("    .byte " + ", ".join("$%02X" % c for c in table[j:j + 12]))
    w("")
    w("disc_level_lo:")
    w("    .byte " + ", ".join("<disc_level_%d" % i for i in range(len(LEVELS))))
    w("disc_level_hi:")
    w("    .byte " + ", ".join(">disc_level_%d" % i for i in range(len(LEVELS))))
    w("")
    w("; The characters themselves, eight bytes each, in code order from")
    w("; DISC_GLYPH_FIRST.  charset.s copies them into the set it builds in RAM.")
    w(".export disc_bitmaps")
    w("disc_bitmaps:")
    for bits in order:
        w("    .byte " + ", ".join("$%02X" % b for b in bits))
    w("")

    inc = [
        "; disc_glyphs.inc — how much of the character set the disc takes",
        "; Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>",
        ";",
        "; Generated by tools/gen_disc.py.  Do not edit: change the generator.",
        ";",
        "; The characters land in the two runs the text set leaves free, $40-$7F",
        "; and $C0-$FF, so charset.s copies them as two blocks.",
        "",
        "DISC_BLOCK1_CODE = $40",
        "DISC_BLOCK1_COUNT = %d" % min(len(order), 64),
        "DISC_BLOCK2_CODE = $C0",
        "DISC_BLOCK2_COUNT = %d" % max(0, len(order) - 64),
        "",
    ]
    open(path.rsplit(".", 1)[0] + ".inc", "w").write("\n".join(inc))
    open(path, "w").write("\n".join(out) + "\n")
    print("%s: %d cells, %d shapes, %d characters"
          % (path, W * H, len(classes) - 1, len(order)))


if __name__ == "__main__":
    main(sys.argv[1])
